"""Fixed skill and job relation

Revision ID: 64a841b10950
Revises: 6dd925dbf829
Create Date: 2024-11-04 15:16:34.909841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a841b10950'
down_revision = '6dd925dbf829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint('skills_job_id_fkey', type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('skills_job_id_fkey', 'jobs', ['job_id'], ['id'])

    op.drop_table('job_skills')
    # ### end Alembic commands ###
